flagception:
    features:
        transcoding:
            default: false
        add_mount_path:
            default: false
        export_data:
            default: false
        registration:
            default: false
        forgot_password:
            default: false
        subdomains:
            default: false
