liip_imagine:
    driver: "gd"
    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public"
                locator: filesystem_insecure
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"
    cache: default
    data_loader: default
    twig:
        mode: lazy
    filter_sets:
        avatar:
            quality: 90
            format: 'png'
            filters:
                thumbnail: { size: [200, 200], mode: outbound }
        background:
            quality: 95
            format: 'png'
            filters:
                scale: { dim: [1920, 1080] }
        favicon:
            quality: 70
            format: 'ico'
            filters:
                thumbnail: { size: [32, 32], mode: outbound }
        logo:
            quality: 95
            format: 'png'
            filters:
                thumbnail: { size: [240, 240], mode: outbound }
        splashscreen:
            quality: 95
            format: 'png'
            filters:
                scale: { dim: [640, 480] }
        app:
            quality: 95
            format: 'png'
            filters:
                scale: { dim: [300, 300] }
