# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.mail_protocol: '%env(MAIL_PROTOCOL)%'
    app.mail_parameters: '%env(MAIL_PARAMETERS)%'
    app.smtp_timeout: '%env(SMTP_TIMEOUT)%'
    project_dir: '%kernel.project_dir%'
    app.provider: '%env(PROVIDER)%'
    app.mediaease_init: '%env(MEDIAEASE_INIT)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Liip\ImagineBundle\Service\FilterService:
        alias: liip_imagine.service.filter
        public: false
        
    Liip\ImagineBundle\Imagine\Cache\CacheManager:
        alias: liip_imagine.cache.manager
        public: false

    Liip\ImagineBundle\Imagine\Data\DataManager:
        alias: liip_imagine.data.manager
        public: false

    Liip\ImagineBundle\Imagine\Filter\Loader\ScaleFilterLoader:
        tags: ['liip_imagine.filter.loader']

    Liip\ImagineBundle\Imagine\Filter\Loader\ThumbnailFilterLoader:
        tags: ['liip_imagine.filter.loader']
    App\Form\Extension\IconButtonExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ButtonType }
    App\Service\PendingActivationService:
        arguments:
            $projectDir: '%project_dir%'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
